spring:
  profiles:
    active: dev
---
server:
  port: 8081
  servlet:
    session:
      timeout: 2h

mybatis-plus:
  # xml扫描，多个目录用逗号或者分号分隔（告诉 Mapper 所对应的 XML 文件位置）
  mapper-locations: classpath:com/ci/mapper/*.xml
  # 以下配置均有默认值,可以不设置
  global-config:
    db-config:
      #主键类型 AUTO:"数据库ID自增" INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: auto
      #字段策略 IGNORED:"忽略判断"  NOT_NULL:"非 NULL 判断")  NOT_EMPTY:"非空判断"
      field-strategy: NOT_EMPTY
      #数据库类型
      db-type: MYSQL
  configuration:
    # 是否开启自动驼峰命名规则映射:从数据库列名到Java属性驼峰命名的类似映射
    map-underscore-to-camel-case: true
    # 如果查询结果中包含空值的列，则 MyBatis 在映射的时候，不会映射这个字段
    call-setters-on-nulls: true
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.43.187.158:3306/shop-dev?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: chen0809
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: chen0809
    timeout: 3000
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0


mybatis:
  mapper-locations: classpath*:com.ci.mapper/*.xml

alipay:
  appId: 9021000129619463
  publicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAhK3qBeGBHI+ZQbi7mx0glxzs10456ffhCOTGUCtpkFcJwTQTxBAWHJrH9BDlMn4vj4+lpmMGxX8TJwRdj8UQU7MSdz0c/VyGcUMlTi1H+gnfSjaF586SKTFIjkA8ShW7wfjRnCz88/Okrt7X+bEisD90McTOrQfO1yJ/IEuDbix1wVt/qer4cnnyIi9vOkkLuiECR5XSFTvgZy8oKa9SDl52UShoHdrVpc7Hc+UWmDUdyp8ed83igg52iyFQdfte0gOb7r3OitRmN0GRdlxllwVa/JvILNdvKrd1UDsoNvjrDXZoxMuNY4MlWdM+ZNoLU/GJEu9penN+Rlz1Wtz8jwIDAQAB
  privateKey: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCAfPv2tOI2HA2ZMgWmN/wrRzJ1EGPcS+zu06dg1FQlFU7bE23ObpoQmestnrdRFHnEr2423WRPFj0red/LA8RiRfpiRIKe0Fzfiv6uKTALHKow0AqLiYLQjduOpbFAZNrDkly7t8MQ/5JMuTStarLiSlDkss9Z+coENmOy4d/fhAQv6VOQazf02aaHCFYfEETwNT2hz62XNrQAePTcuoK6s2b+r6KMlDowA8w/nNV1Xm09/VG+YYaLQDnlqDXBs7I9DRkZB4o3hNpviJx2XCBCYRTrFy3k6iQ0D7I/ntJNRGmD5pXg25N5GiLK3OcRjxTU5vhlKSat1Ud9PEbWVadnAgMBAAECggEAHVVraK1vH49UA2+KHqKVbYP5nwQ46ChlVTj484BGHZk5wYY0AXb6sWOSb33WuCoGisLKVLhCmFOpb22JjB22DgGP4jNl5sAHE/n1nulEUKUgrbgxUB36wYZBY9WsG9lqoE+f4DNZ012lluKJhjXf1Q3GXg/8irweRMvuAv7ST4LPaVOYp1o8UWiUhjoV50+cGri6r/5v+tVsdKIGlBoNisSBpULxsPaSlRNJODS/CQ9e44QU8j8gfsmW/uALJBJc303fFTnzO4jMbHKheaLwjbEGFRbHGg9aoHOVZwxr8rcVDVJsPDsS1s6GjBJlWciOjPW4vmnQ6R7qpzFHGLzioQKBgQC28314UhcHFxkXgRRtU+C7LbRxI7BLY/eGGW3q6wWaXAsZqQVJ6s14oQBMU82RCcivvsEdZKAHopI5IQUGbe/M7vAf94SpEi0AC6T0MK8Us5Fd2kmT1f4iqYJQVOr1H9qdYnBLOJc3W+yjQHwSoQUyX1BOqLMePuOjetHWrSf0GQKBgQCzyoUTsLYQ16VJVmTDxyfzhzhDMIbMBV4x3v5BCUYBtncWLQlBmnumoi3b6cqO0WHulmt0ViCUmxn4jB9VuFirEX8tkkhjvQF7gs5fr9qFMwGcnJPERX66z89cdwq7R7X5ouzn4xpjRJwtQ+/ypx8Cf17sdoF5V+qyp1uDZGnnfwKBgQCHEqp2JRV/VJxf8BsmxKDNUWdBiPnmD352cVvn73EJkB9Z6KJQ+pyNDUFtGQpSpQiYSJvHmb1VJcATkb9mCdDcWyTKVTKKqTK0L+SvrSn2fMU8p6dfEMU6zi+6I5f9NnFvdXg28Scj5iiGN1vjXSK7GAfwqzjjgccLsegvOVSgMQKBgCu57oGqca1I9S8P7vPahPHqihl1PONzzsPsSwQAQGF8QhxHmb+11ariOKsKgjQX4myHctzZcZUS388eLSTI7++zEq4/rJFtT2X9mzmUaF4K2LKBNkL+7+J5ViJT5W1E9JIhOOLwzeMktaMgqcPnN1iBJ9H0xGqBolgO8efTzRn7AoGAfA0tG8ZkbxVeZmni2UByVtNiIuRE3BvD+V17qQip6bGAR4pH2ACt1mJo7G9dey2jU2L97y8WvG8fYGH9s1i/Wq6k7BclktS62jhpHv9yaAQA7KU8aLHwJnWDzBbFRyiHjCNxWpUGvKUGywjEqSyTvZDn2DQ9RbROBGDOh2eIO7E=
  notifyUrl: http://vuarap.natappfree.cc/alipay/notify
  returnUrl: http://localhost/#/orderDetail?orderId=
  gatewayUrl: https://openapi-sandbox.dl.alipaydev.com/gateway.do
  charset: UTF-8
  format: json
  signType: RSA2

---
server:
  port: 80
  servlet:
    session:
      timeout: 2h

mybatis-plus:
  mapper-locations: classpath:com/ci/mapper/*.xml
  global-config:
    db-config:
      id-type: auto
      field-strategy: NOT_EMPTY
      db-type: MYSQL
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

spring:
  config:
    activate:
      on-profile: pro
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/shop-dev?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: chen0809
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: chen0809
    timeout: 3000
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0


mybatis:
  mapper-locations: classpath*:com.ci.mapper/*.xml

alipay:
  appId: 9021000129619463
  publicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAhK3qBeGBHI+ZQbi7mx0glxzs10456ffhCOTGUCtpkFcJwTQTxBAWHJrH9BDlMn4vj4+lpmMGxX8TJwRdj8UQU7MSdz0c/VyGcUMlTi1H+gnfSjaF586SKTFIjkA8ShW7wfjRnCz88/Okrt7X+bEisD90McTOrQfO1yJ/IEuDbix1wVt/qer4cnnyIi9vOkkLuiECR5XSFTvgZy8oKa9SDl52UShoHdrVpc7Hc+UWmDUdyp8ed83igg52iyFQdfte0gOb7r3OitRmN0GRdlxllwVa/JvILNdvKrd1UDsoNvjrDXZoxMuNY4MlWdM+ZNoLU/GJEu9penN+Rlz1Wtz8jwIDAQAB
  privateKey: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCAfPv2tOI2HA2ZMgWmN/wrRzJ1EGPcS+zu06dg1FQlFU7bE23ObpoQmestnrdRFHnEr2423WRPFj0red/LA8RiRfpiRIKe0Fzfiv6uKTALHKow0AqLiYLQjduOpbFAZNrDkly7t8MQ/5JMuTStarLiSlDkss9Z+coENmOy4d/fhAQv6VOQazf02aaHCFYfEETwNT2hz62XNrQAePTcuoK6s2b+r6KMlDowA8w/nNV1Xm09/VG+YYaLQDnlqDXBs7I9DRkZB4o3hNpviJx2XCBCYRTrFy3k6iQ0D7I/ntJNRGmD5pXg25N5GiLK3OcRjxTU5vhlKSat1Ud9PEbWVadnAgMBAAECggEAHVVraK1vH49UA2+KHqKVbYP5nwQ46ChlVTj484BGHZk5wYY0AXb6sWOSb33WuCoGisLKVLhCmFOpb22JjB22DgGP4jNl5sAHE/n1nulEUKUgrbgxUB36wYZBY9WsG9lqoE+f4DNZ012lluKJhjXf1Q3GXg/8irweRMvuAv7ST4LPaVOYp1o8UWiUhjoV50+cGri6r/5v+tVsdKIGlBoNisSBpULxsPaSlRNJODS/CQ9e44QU8j8gfsmW/uALJBJc303fFTnzO4jMbHKheaLwjbEGFRbHGg9aoHOVZwxr8rcVDVJsPDsS1s6GjBJlWciOjPW4vmnQ6R7qpzFHGLzioQKBgQC28314UhcHFxkXgRRtU+C7LbRxI7BLY/eGGW3q6wWaXAsZqQVJ6s14oQBMU82RCcivvsEdZKAHopI5IQUGbe/M7vAf94SpEi0AC6T0MK8Us5Fd2kmT1f4iqYJQVOr1H9qdYnBLOJc3W+yjQHwSoQUyX1BOqLMePuOjetHWrSf0GQKBgQCzyoUTsLYQ16VJVmTDxyfzhzhDMIbMBV4x3v5BCUYBtncWLQlBmnumoi3b6cqO0WHulmt0ViCUmxn4jB9VuFirEX8tkkhjvQF7gs5fr9qFMwGcnJPERX66z89cdwq7R7X5ouzn4xpjRJwtQ+/ypx8Cf17sdoF5V+qyp1uDZGnnfwKBgQCHEqp2JRV/VJxf8BsmxKDNUWdBiPnmD352cVvn73EJkB9Z6KJQ+pyNDUFtGQpSpQiYSJvHmb1VJcATkb9mCdDcWyTKVTKKqTK0L+SvrSn2fMU8p6dfEMU6zi+6I5f9NnFvdXg28Scj5iiGN1vjXSK7GAfwqzjjgccLsegvOVSgMQKBgCu57oGqca1I9S8P7vPahPHqihl1PONzzsPsSwQAQGF8QhxHmb+11ariOKsKgjQX4myHctzZcZUS388eLSTI7++zEq4/rJFtT2X9mzmUaF4K2LKBNkL+7+J5ViJT5W1E9JIhOOLwzeMktaMgqcPnN1iBJ9H0xGqBolgO8efTzRn7AoGAfA0tG8ZkbxVeZmni2UByVtNiIuRE3BvD+V17qQip6bGAR4pH2ACt1mJo7G9dey2jU2L97y8WvG8fYGH9s1i/Wq6k7BclktS62jhpHv9yaAQA7KU8aLHwJnWDzBbFRyiHjCNxWpUGvKUGywjEqSyTvZDn2DQ9RbROBGDOh2eIO7E=
  notifyUrl: http://shop.cikian.cn/alipay/notify
  returnUrl: http://shop.cikian.cn/#/orderDetail?orderId=
  gatewayUrl: https://openapi-sandbox.dl.alipaydev.com/gateway.do
  charset: UTF-8
  format: json
  signType: RSA2
---
